service: pizzaria

frameworkVersion: '2'
provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
  eventBridge:
    useCloudFormation: true

functions:
  allEvents:
    handler: handler.allEventsHandler
    events:
      - eventBridge:
          eventBus:
            - arn:aws:events::${AWS::Region}::${AWS::AccountId}:event-bus:/pizzaria
          pattern:
            source:
              - com.pizza.status
  ready:
    handler: handler.readyHandler
    events:
      - eventBridge:
          eventBus:
            - arn:aws:events:${AWS::Region}::${AWS::AccountId}:event-bus:/pizzaria
          pattern:
            source:
              - com.pizza.status
            detail-type:
              - Alteracao Pizza
            detail:
              status:
                - pronto